name: Tools - Docker Build Test

on:
  pull_request:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  docker-build-image:
    name: Docker Build Image
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - image: wydler/parsedmarc-elasticsearch
            dockerfile: ./elasticsearch/docker/Dockerfile

          - image: wydler/parsedmarc-geoipupdate
            dockerfile: ./geoipupdate/docker/Dockerfile

          - image: wydler/parsedmarc-kibana
            dockerfile: ./kibana/docker/Dockerfile

          - image: wydler/parsedmarc-nginx
            dockerfile: ./nginx/docker/Dockerfile

          - image: wydler/parsedmarc-app
            dockerfile: ./parsedmarc/docker/Dockerfile

          - image: wydler/parsedmarc-utils
            dockerfile: ./utils/docker/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ vars.DOCKER_USER_REPO }}

      - name: Build docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
