---
name: "Tools - Validate Dockerfile Schema"

"on":
  pull_request:
    branches: [ "master" ]

jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Validate Dockerfile files
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5  # v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: "DL3008,DL3013,DL3015,DL3018"
